[project]
name = "rl-3ngine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tcod>=19.4.0",
    "tcod-camera>=1.0.1",
    "tcod-ecs>=5.4.1",
]
